### ISSUE TITLE
关于 LRW 数据集的测试和评估时长的咨询

### ISSUE THREAD

**Issue by laura990501** [yuangan/evaluation_eat#6]
作者您好！非常感谢您分享了 LRW 数据集的评估代码！

我想咨询一下 LRW 数据集的**测试和评估**所需要的时长。因为我在 2 卡的 3090 机器上需要跑很长的时间，所以想咨询一下您用了多长时间，并想请问您是否能提供相关 log。

再次感谢您的帮助！

**Comment by yuangan** [comment]
挺久的，因为LRW数据量特别大，25000张图片的预处理就要半天。预处理完成后，1张3090测完整个流程需要大概一天，建议你处理好数据之后，先用test_psnr_ssim_sync_lrw_100.sh测试一下代码是否正常。100帧的测试结果应该输出如下，由于环境不同结果可能会有一点区别，但应该不会太大：
![image](https://github.com/yuangan/evaluation_eat/assets/12268263/f3827b89-a7b3-462a-9dc6-eabe212b870f)

**Comment by laura990501** [comment]
非常感谢！

**Comment by yuangan** [comment]
:smile:
